Fix false positive non-utf symlinks reported
oamg/leapp-repository pull request #1052
Opened 2023-03-08 11:14 UTC by fernflower

Because of botched up check for python2 valid utf symlinks were reported as non-utf ones.

OAMG-8629

2023-03-08 13:09 UTC, fernflower commented
/rerun

2023-03-09 15:26 UTC, pirat89 commented
@fernflower As the previous tests has not caught the problem before, is the particular test that discovered the issue now part of the executed integration tests for the PR? If so, do you know the name? Just tried to search for "root" i could not find anything related. From my understanding, such a test exists, so if it's not executed now, possibly it could be added to the set? Otherwise it would be nice to prepare unit-test so it's covered. But missing tests is not blocker from my POV for the merge right now. Can be tested manually still. The fix seems reasonable to me, haven't tested it yet.

2023-03-09 16:09 UTC, fernflower commented
@pirat89 Yeah, there is a test, it's MR199 to the integration tests in gitlab. We just decided not to merge the MR before the leapp change gets in not to cause extra failures.

2023-03-14 11:07 UTC, fernflower commented
/rerun

2023-03-22 12:31 UTC, fernflower commented
/packit build

2023-03-23 12:33 UTC, pirat89 requested changes
the current implementation leads to traceback:
```
# mkdir /root/břeťa
# ln -s /root/břeťa/ bobošík
# leapp preupgrade --debug
...
2023-03-23 13:27:17.925 INFO     PID: 26891 leapp.workflow: Workflow finished due to the until-phase flag
2023-03-23 13:27:17.932 INFO     PID: 26891 leapp: Answerfile will be created at /var/log/leapp/answerfile
Traceback (most recent call last):
  File "/usr/bin/leapp", line 9, in <module>
    load_entry_point('leapp==0.15.1', 'console_scripts', 'leapp')()
  File "/usr/lib/python2.7/site-packages/leapp/cli/__init__.py", line 45, in main
    cli.command.execute('leapp version {}'.format(VERSION))
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 111, in execute
    args.func(args)
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 133, in called
    self.target(args)
  File "/usr/lib/python2.7/site-packages/leapp/cli/commands/upgrade/breadcrumbs.py", line 163, in wrapper
    return f(*args, breadcrumbs=breadcrumbs, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/cli/commands/preupgrade/__init__.py", line 78, in preupgrade
    util.generate_report_files(context, report_schema)
  File "/usr/lib/python2.7/site-packages/leapp/cli/commands/upgrade/util.py", line 148, in generate_report_files
    generate_report_file(messages, context, report_txt, report_schema)
  File "/usr/lib/python2.7/site-packages/leapp/utils/report.py", line 121, in generate_report_file
    f.write('Remediation: {}\n'.format(remediation))
  File "/usr/lib/python2.7/site-packages/leapp/reporting/__init__.py", line 283, in __repr__
    return "\n".join([repr(r) for r in self._remediations])
  File "/usr/lib/python2.7/site-packages/leapp/reporting/__init__.py", line 248, in __repr__
    return "[{}] {}".format(self._value['type'], ' '.join(self._value['context']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0159' in position 20: ordinal not in range(128)
```

2023-03-23 16:52 UTC, fernflower commented on commands/upgrade/breadcrumbs.py
> +            # NOTE(ivasilev) this can happen if LEAPP_DEVEL_TARGET_RELEASE is specified and pointing to an impossible
Removed the comment, checking for env var presence is pretty self-explanatory. Thanks

2023-03-23 16:52 UTC, fernflower commented
/rerun

2023-03-24 11:19 UTC, fernflower commented
@pirat89 Should be ok now. I added a unit test with several test cases + verified manually on rhel7 and rhel8.

2023-03-24 11:19 UTC, fernflower commented
/rerun

2023-03-26 20:57 UTC, pirat89 commented
@fernflower seems good. I will do the last manual test on monday, but it seems good so far. thanks for covering it by unit tests also!!

2023-03-26 21:34 UTC, fernflower commented
@pirat89 Sure, my bad I didn't do that in the first iteration. Thanks for reviewing

2023-04-03 10:40 UTC, fernflower commented
(just to reflect our internal slack discussion)
Unfortunately, can't reproduce neither manually nor with an integration test :(

2023-04-05 16:52 UTC, fernflower commented
Finally I got this captured by unittests in framework https://github.com/oamg/leapp/pull/821 , phew.
So, the full picture is as follows - my fix for this PR1052 didn't actually introduce a regression, but has uncovered the behavior (the faulty one) that has always been there with non-ascii strings in the report. More specifically, the Remediation object (which is the most likely place for non-ascii strings to emerge) doesn't handle utf-8 properly in it's `repr`method. But as valid-utf8 symlinks have been erroneously discovered as invalid non-utf8 ones, their remediation have been never printed until I fixed the discovery in this PR.
Hope it makes some sense for anyone who reads it :) 
To be on the safe side we could make leapp#821 and leapp-repository#1052 co-dependent.

2023-04-13 11:22 UTC, fernflower commented
/rerun

2023-04-14 12:40 UTC, fernflower commented
/rerun

2023-04-17 10:30 UTC, fernflower commented
/packit build

2023-04-19 09:23 UTC, fernflower commented
/packit test

2023-04-21 14:42 UTC, fernflower commented
/rerun 821

2023-04-25 09:19 UTC, fernflower commented
/packit test oamg/leapp#821

2023-04-26 12:11 UTC, pirat89 approved these changes
The fix in framework has been merged in upstream. Manually tested, seems it works as it should. Merging \o/

2023-04-26 12:23 UTC, merged