el8toel9: Warn about deprecated Xorg drivers
oamg/leapp-repository pull request #1078
Opened 2023-05-05 09:51 UTC by ofourdan

Some Xorg drivers have been deprecated in favor of the "modesetting" driver.

If Xorg is configured to use those driver, it may not be able to work properly after the upgrade.

Add a new actor to check in the journal whether such Xorg drivers are in use and in that case, also warn if there are custom Xorg config options.

Known limitation: This actor checks the journal logs since the last boot, meaning that if Xorg was started manually from a console or if the system has been rebooted after a graphical Xorg session was used, the actor will not be able to detect the use of deprecated drivers.

2023-05-05 12:06 UTC, fernflower commented
/packit test

2023-05-05 14:33 UTC, pirat89 requested changes
I found several problems that are describe in below with explanations. But I am also curious, how the manual removal of these drivers makes the graphical session working after the upgrade? And are these drivers deprecated or removed on RHEL 9? In case they are removed, than only thing that happened during the upgrade is that packages with these drivers will be removed. What is then difference from the manual removal? Is it than enough to just uninstall such drivers?

2023-05-09 09:03 UTC, ofourdan commented
> […]But I am also curious, how the manual removal of these drivers makes the graphical session working after the upgrade?

The modesetting driver should be used instead.

> And are these drivers deprecated or removed on RHEL 9?

They are removed.

> In case they are removed, than only thing that happened during the upgrade is that packages with these drivers will be removed. What is then difference from the manual removal? Is it than enough to just uninstall such drivers?

This is mostly about warning users/sysadmins.

By default, the modesetting driver would be used, but in el8 we would still ship the various hardware specific Xorg drivers and people could install them and add an entry in xorg.conf to use them, sometimes even with driver specific options.

In that case, it's up to the user/sysadmin to remove the driver (and the relevant xorg,conf entries) prior to upgrade, because Xorg will refuse to start if the xorg.conf refers to a driver which is not available.

2023-05-10 13:07 UTC, ofourdan commented
> I see. But in such a case the instructions in the report are missleading as you do not want from user just a driver removal, you want them also to update the related configuration file. IIUC

Yes, I'm working on it, and the refactoring :)

2023-05-11 08:50 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/actor.py
> +                   ])
Rewritten

2023-05-11 08:50 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/libraries/xorgdriverlib.py
> +        run(['check_syslog_for_driver.sh', _driver])
Fixed, there are now two separate actors, one for facts, another one for check.

2023-05-11 08:51 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/tools/check_syslog_for_driver_config.sh
> +  exit -1
That code is removed now.

2023-05-11 08:51 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/tools/check_syslog_for_driver_config.sh
> +  echo Usage: $0 DRIVER
That code is removed now.

2023-05-11 08:51 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/tools/check_syslog_for_driver.sh
> +        /usr/bin/grep -q -F $1
That code is removed now.

2023-05-11 08:51 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/tools/check_syslog_for_driver.sh
> +  exit -1
That code is removed now.

2023-05-11 08:51 UTC, ofourdan commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/tools/check_syslog_for_driver.sh
> +  echo Usage: $0 DRIVER
That code is removed now.

2023-05-22 15:08 UTC, pirat89 commented
/packit build

2023-05-22 15:13 UTC, pirat89 commented on repos/system_upgrade/el8toel9/actors/checkxorgdeprecateddrivers/actor.py
> +                   ])
Seems good to me.

2023-05-22 15:19 UTC, pirat89 reviewed
@ofourdan seems good to me. Would  you mind to add some unit tests for our peace of mind? Otherwise it seems good.

2023-05-26 13:14 UTC, ofourdan commented
> @ofourdan seems good to me. Would you mind to add some unit tests for our peace of mind? Otherwise it seems good.

Thanks! I added some unit tests for the report. For the fact/check, it's not so simple as it basically gets the data from the journal logs.

2023-05-29 13:25 UTC, pirat89 commented
@ofourdan thanks! In case of journal log, I think it's ok to just mock the `run` function to return content of some files - or just strings directly. E.g. like here: https://github.com/oamg/leapp-repository/blob/777e0a641739add1fca50af774d6d924af5550d7/repos/system_upgrade/common/actors/storagescanner/tests/unit_test_storagescanner.py#L257

It's not even needed to check exact the command parameters when it's not created dynamically and there are not multiple shell commands called in a tested function. In that particular example, it present also reading from files stored under ...../tests/files/  - see `CUR_DIR` lines. If you share some (crafted) examples of expected outputs, we can help you with the unit tests for the facts scanner.

I am sorry for late responses, we have couple of priority things on the plate last weeks and today we got anothers. I expect we will get to this PR during Thu/Fri this week.

2023-06-05 11:26 UTC, ofourdan commented
Added the Xorg log files to the codespell's list of skipped files.

2023-06-06 17:15 UTC, pirat89 approved these changes
lgtm. thanks for your work! waiting for the test results. Btw, in case of failures some of upgrades tests (testing farm), it could be caused by some infrastructure issues. we will check them once they are present in case they are of failures.

2023-06-06 17:22 UTC, pirat89 commented
/packit test

2023-06-14 09:58 UTC, ofourdan commented
Hi Petr, anything else left for me to do for this?

2023-06-19 15:28 UTC, pirat89 commented
@ofourdan Hi \o sorry for the late response. seems that nothing else is needed. I will rerun the regression tests one more time. Hopefully the infrastructure is working still

2023-06-19 15:29 UTC, pirat89 commented
/packit test

2023-06-19 21:02 UTC, pirat89 commented
Checking the current test results (somewhere around 50% finished, for a reason, there are no capacities in testing farm)

2023-06-19 21:04 UTC, merged

2023-06-20 06:23 UTC, ofourdan commented
Woohoo! Thanks!