overlay lib: Secure the creation of the disk image when size is < 130
oamg/leapp-repository pull request #1103
Opened 2023-07-31 09:39 UTC by pirat89

In case the filesystem for which the disk img is going to be created has very small amount of free space (under 130 MiBs), it cannot be formatted by XFS with current params.

This could be hit in several cases:
 * the system partition/volume - in this case, most likely an issue will be hit anyway later by DNF speaking about small amount of free space if a content is installed inside by RPMs as such a small amount of free space is really not expected to see at all
 * it's a data mount point (e.g. iso) or a filesystem type that should by part of the OVERLAY_DO_NOT_MOUNT set, so enlarging the value to 130 MiBs should not affect anything negatively at all
 * in case of /boot, the problem with the free space is covered already in a different actor prior we try to create any disk img, so we are safe here

Based on arguments above, I am considering setting the 130 MiBs as minimal value safe for in-place upgrades. Also it will allow to skip possible problems with specific file systems (like tmpfs, ...) in case we are still missing some in the OVERLAY_DO_NOT_MOUNT - and kind of read only storage (such as iso9660, etc..).

2023-07-31 09:44 UTC, pirat89 commented
@oamg/developers  another aproach would be just to keep the error message. but I started to think about cases that we are still missing and that there could be actually some mountpoints that cannot be enlarged (like iso...not sure why someone would put that in fstab, but...) or mounpoints that we should actually ignore. wdyt about that? In case we do not want to set a minimum limit, we can just update the error msg in a way we inform user what partition/volume does not contain enough free space.

Need to still keep in mind that this whole problem is about corner cases.

2023-07-31 10:27 UTC, pirat89 commented
/rerun

2023-08-16 14:18 UTC, MichalHe commented
/packit build

2023-08-16 14:52 UTC, MichalHe requested changes
I've tested the patch with a `256mb` partition that contains `200mb` file, and the patch works as expected - preupgrade finished without problems, whereas without this patch the preupgrade fails.

Logs produced by this patch:
```
2023-08-16 14:45:48.454 WARNING  PID: 15114 leapp.workflow.TargetTransactionCheck.dnf_transaction_check: The apparent size for the disk image representing {path} is too small ({} MiBs) for a formatting. Setting 130 MiBs instead.
2023-08-16 14:45:48.455 DEBUG    PID: 15114 leapp.workflow.TargetTransactionCheck.dnf_transaction_check: Attempting to create disk image at /var/lib/leapp/scratch/diskimages/root_mnt
2023-08-16 14:45:48.456 DEBUG    PID: 15114 leapp.workflow.TargetTransactionCheck.dnf_transaction_check: External command has started: ['/bin/dd', 'if=/dev/zero', 'of=/var/lib/leapp/scratch/diskimages/root_mnt', 'bs=1M', 'count=0', 'seek=130']
```
@pirat89 please fix the minor issues found and I will approve this no problemo.

2023-08-16 14:52 UTC, MichalHe commented on repos/system_upgrade/common/libraries/overlaygen.py
> +            ' is too small ({} MiBs) for a formatting. Setting 130 MiBs instead.'
This warning does not have its placeholders formatted (a missing `.format` perhaps)

2023-08-16 14:52 UTC, MichalHe commented on repos/system_upgrade/common/libraries/overlaygen.py
> +            message='Cannot create XFS filesystem in{}'.format(diskimage_path),
```suggestion
            message='Cannot create XFS filesystem in {}'.format(diskimage_path),
```

2023-08-16 14:52 UTC, MichalHe commented on repos/system_upgrade/common/libraries/overlaygen.py
> +            message='Cannot create Ext4 filesystem in{}'.format(diskimage_path),
```suggestion
            message='Cannot create Ext4 filesystem in {}'.format(diskimage_path),
```

2023-08-16 15:31 UTC, MichalHe approved these changes

2023-08-17 08:21 UTC, MichalHe commented
/rerun

2023-08-17 13:50 UTC, pirat89 commented
Tests passed. Merging \o

2023-08-17 13:51 UTC, merged