checknfs: do not check systemd mounts
oamg/leapp-repository pull request #1127
Opened 2023-09-14 11:49 UTC by MichalHe

Optional, keeping this code breaks nothing, however, the inhibitor cannot be reproduced.

Systemd mounts contain only *block* devices. Therefore, the list can never contain NFS shares at all and the check is redundant. This is apparent if one reads storagescanner/libraries/storagescanner.py:L251. This patch, therefore, removes the check for systemd mount alltogether.

@pirat89 @fernflower @matejmatuska

2023-09-15 11:57 UTC, fernflower commented
I have used your pr's build for some unrelated upgrade testing and ended up with a crash
```
2023-09-15 07:48:24.63  INFO     PID: 4727 leapp.workflow.Checks: Executing actor check_nfs 
Process Process-370:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/repository/actor_definition.py", line 74, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/actors/__init__.py", line 289, in run
    self.process(*args)
  File "/etc/leapp/repos.d/system_upgrade/common/actors/checknfs/actor.py", line 44, in process
    if any(fstab_nfs_mounts, nfs_mounts):
TypeError: any() takes exactly one argument (2 given)
2023-09-15 07:48:24.183 ERROR    PID: 4727 leapp.workflow.Checks: Actor check_nfs has crashed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/leapp/repository/actor_definition.py", line 74, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/actors/__init__.py", line 289, in run
    self.process(*args)
  File "/etc/leapp/repos.d/system_upgrade/common/actors/checknfs/actor.py", line 44, in process
    if any(fstab_nfs_mounts, nfs_mounts):
TypeError: any() takes exactly one argument (2 given)
```
I believe the rest of the tests failed for this particular reason as well

2023-09-15 11:58 UTC, fernflower requested changes
Please fix the traceback

2023-09-15 18:45 UTC, MichalHe commented
@fernflower Thanks, should be fixed.

2023-09-18 10:42 UTC, fernflower commented
/packit build

2023-09-19 05:39 UTC, fernflower commented
/packit build

2023-09-19 13:57 UTC, MichalHe commented
@fernflower It isn't that you cannot mount a NFS share using systemd-mount, its that the `systemd_mounts` entry contains only block devices, see [storagescanner](https://github.com/oamg/leapp-repository/blob/4d8ad1c0363fc21f5d8a557f3319a6efacac9f2a/repos/system_upgrade/common/actors/storagescanner/libraries/storagescanner.py#L241), see https://stackoverflow.com/questions/58914555/nfs-mount-point-as-a-disk-device-linux

2023-10-02 13:25 UTC, fernflower commented
/packit build

2023-10-06 12:16 UTC, pirat89 commented
/packit test

2023-10-06 12:17 UTC, pirat89 approved these changes
It make sense. code lgtm. waiting for tests (restarted as they stucked)

2023-11-03 15:24 UTC, pirat89 commented
Rebased. hopefully tests will pass now.

2023-11-10 16:30 UTC, merged