feature: add possibility to use net.naming-scheme
oamg/leapp-repository pull request #1215
Opened 2024-04-29 09:19 UTC by MichalHe

Add a possibility to use the net.naming-scheme cmdline argument to make immutable network interface names during the upgrade. The feature can be used only for 8>9 upgrades and higher. To enable the feature, use `LEAPP_USE_NET_NAMING_SCHEME=1`.

2024-09-02 20:04 UTC, MichalHe commented
I have tested the PR using a rhel8 system running on real HW with a NIC that would be renamed during the upgrade. The solutions installed the `rhel-net-naming-sysattrs` package to the target system, the NIC names were consistent, and the post-upgrade system was booted with `net.naming-scheme=rhel-8.10`.

2024-09-04 14:17 UTC, matejmatuska requested changes
Code-wise seems okay, just some minor comments.

I know RHEL7 is EOL, but maybe you could check if the `LEAPP_USE_NET_NAMING_SCHEME` envar is set for 7->8 upgrade. I would expect at least a warning message in the logs, since we can't and won't do what the user explicitly wants.

I haven't tested the code yet.

2024-09-05 18:06 UTC, MichalHe commented on repos/system_upgrade/el8toel9/actors/emit_net_naming_scheme/tests/test_emit_net_naming_scheme.py
> +        pass
Suggestion applied, thank you.

2024-09-05 18:06 UTC, MichalHe commented on repos/system_upgrade/common/actors/addupgradebootentry/tests/unit_test_addupgradebootentry.py
> +>>>>>>> afb7fe51 (late_kernel_cmdline: break dependency loop)
Cool, silly me. Should be fixed.

2024-09-05 18:06 UTC, MichalHe commented on repos/system_upgrade/common/actors/addupgradebootentry/libraries/addupgradebootentry.py
> +    # the removal of undesired args we must call grubby in a separate call
I have reworded it

2024-09-05 18:08 UTC, MichalHe commented on repos/system_upgrade/common/actors/addupgradebootentry/libraries/addupgradebootentry.py
> +        args_sorted = sorted(args_to_remove, key=lambda arg: arg.key)
Of course - for deterministic testing

2024-09-05 18:12 UTC, MichalHe commented on repos/system_upgrade/el8toel9/actors/emit_net_naming_scheme/libraries/emit_net_naming.py
> +    api.current_logger().info(msg, 'yes' if is_compatible else 'no')
Oky :)

2024-09-05 18:44 UTC, MichalHe commented on repos/system_upgrade/common/actors/addupgradebootentry/libraries/addupgradebootentry.py
> +    return args_str
removed

2024-10-03 14:51 UTC, matejmatuska commented
/packit copr-build

2024-10-21 20:40 UTC, MichalHe commented
/packit build

2024-10-22 20:02 UTC, matejmatuska commented
/packit retest-failed

2024-10-22 20:04 UTC, matejmatuska commented
Tested, now works as expected.

PLease rebase and resolved conflicts.

2024-10-22 20:35 UTC, MichalHe commented
@matejmatuska rebased

2024-11-05 13:34 UTC, pirat89 commented
/packit copr-build

2024-11-06 23:05 UTC, matejmatuska approved these changes
For now this is only going to be enabled on 8->9.

The `persistentnamesconfig` actor is now properly skipped on paths other than 8->9 and `emit_net_naming_scheme` only emits on 8->9.
I tested it and it works as expected. LGTM

2024-11-07 12:38 UTC, merged