mount /usr: Implement try-sleep loop - add time for storage initialis…
oamg/leapp-repository pull request #1218
Opened 2024-05-03 12:48 UTC by pirat89

…ation

This problem is typical for SAN + FC when the storage needs sometimes more time for the initialisation. Implemented try-sleep loop. Retry the activation of the storage + /usr mounting in 15s. The loop can be repeated 10 times, so total time is 150s right now for the activation.

jira: https://issues.redhat.com/browse/RHEL-3344

2024-05-03 14:01 UTC, MichalHe requested changes

2024-05-03 14:01 UTC, MichalHe commented on repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
> +    warn "Failed attempt to initialize the storage. Retry in $_sleep_timeout seconds. Attempt: $0 of 10"
```suggestion
    warn "Failed attempt to initialize the storage. Retry in $_sleep_timeout seconds. Attempt: $i of 10"
```

2024-05-03 14:09 UTC, pirat89 commented on repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
> +          if [ "$1" != "true" ]; then
I thought this could be caught :D let's call it everywhere `_last_attempt`  then.

2024-05-03 14:11 UTC, pirat89 commented on repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
> +    warn "Failed attempt to initialize the storage. Retry in $_sleep_timeout seconds. Attempt: $0 of 10"
fixed

2024-05-03 14:11 UTC, pirat89 commented on repos/system_upgrade/common/actors/commonleappdracutmodules/files/dracut/85sys-upgrade-redhat/mount_usr.sh
> +          if [ "$1" != "true" ]; then
changed.

2024-05-03 14:53 UTC, pirat89 commented
Manual testing on my LVM VMs:
* Seems it passed correctly on my several setups. Successfully upgraded system without seeing any errors.
* Note that I haven't tested the scenario when the storage needs more time for the initialisation.

Lsblk from tested machines (used multiple VGs): 
```
[root@localhost ~]# lsblk
NAME           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda            252:0    0   30G  0 disk 
├─vda1         252:1    0  200M  0 part /boot/efi
├─vda2         252:2    0    1G  0 part /boot
├─vda3         252:3    0    7G  0 part 
│ └─rhel00-var 253:3    0    7G  0 lvm  /var
├─vda4         252:4    0    4G  0 part 
│ ├─rhel-root  253:0    0    2G  0 lvm  /
│ └─rhel-swap  253:1    0    2G  0 lvm  [SWAP]
└─vda5         252:5    0    6G  0 part 
  └─rhel01-usr 253:2    0    6G  0 lvm  /usr
```

```
[root@localhost ~]# lsblk
NAME           MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda            252:0    0  30G  0 disk 
├─vda1         252:1    0   1G  0 part /boot
├─vda2         252:2    0   8G  0 part 
│ └─rhel00-var 253:3    0   7G  0 lvm  /var
├─vda3         252:3    0   7G  0 part 
│ └─rhel01-usr 253:2    0   6G  0 lvm  /usr
├─vda4         252:4    0   1K  0 part 
└─vda5         252:5    0   6G  0 part 
  ├─rhel-root  253:0    0   3G  0 lvm  /
  └─rhel-swap  253:1    0   2G  0 lvm  [SWAP]
vdb            252:16   0  20G  0 disk 
```

```
[root@localhost ~]# lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda           252:0    0   20G  0 disk 
├─vda1        252:1    0  500M  0 part /boot/efi
├─vda2        252:2    0  500M  0 part /boot
└─vda3        252:3    0   19G  0 part 
  ├─rhel-root 253:0    0    4G  0 lvm  /
  ├─rhel-swap 253:1    0    2G  0 lvm  [SWAP]
  ├─rhel-usr  253:2    0    8G  0 lvm  /usr
  └─rhel-var  253:3    0    5G  0 lvm  /var
```

2024-05-03 15:02 UTC, MichalHe approved these changes
Code looks OK, I've tried upgrading with the patch myself using a simple setup. As the results on more complex LVM setups conducted by @pirat89 we positive, I am merging this.

2024-05-03 15:02 UTC, merged

2024-05-03 16:03 UTC, rmetrich commented
Sorry I don't like that proposal much, because it happens the `sleep xxx` helps in many other cases than having a dedicated `/usr`, in fact customer cases showed that it helps as soon as more than a few LVM LVs are present.
Hence I would suggest that even if there is no `/usr` to wait for, sleep at least a round (15 seconds).

2024-05-04 07:59 UTC, pirat89 commented
@rmetrich  thanks for the feedback. Shouldn't be that covered by the LVM activation that's checked and happens before the mount_usr is called? I hoped that it could catch it