Enable IPU path 8.10 -> 9.5
oamg/leapp-repository pull request #1245
Opened 2024-05-28 12:25 UTC by matejmatuska

* Enable 9.5 target
* Add RHEL 9.5 product certificates

2024-05-28 12:29 UTC, pirat89 requested changes

2024-05-28 12:29 UTC, pirat89 commented on repos/system_upgrade/common/files/upgrade_paths.json
> +        "8": ["9.4", "9.2", "9.5"]
@matejmatuska  sap hana is not supported for odd. it sould stay untouched.

2024-05-28 12:35 UTC, pirat89 approved these changes
lgtm

2024-05-28 13:40 UTC, pirat89 commented
@matejmatuska  seems we cannot allow it yet. so let's drop the change in tests and put it into a separate PR.

2024-05-29 08:36 UTC, matejmatuska commented
> @matejmatuska seems we cannot allow it yet. so let's drop the change in tests and put it into a separate PR.

Ok, I dropped the commit.

2024-05-29 13:03 UTC, matejmatuska commented
/packit test

2024-05-30 11:45 UTC, pirat89 approved these changes
lgtm

2024-05-30 11:45 UTC, merged