Update .packit.yaml config
oamg/leapp-repository pull request #1252
Opened 2024-06-06 07:16 UTC by mm0ran

- Remove unused RHSM_REPOS and LEAPPDATA_BRANCH
- Remove enabling repos step from .packit.yaml, it was moved to TF, where it logically belongs to.
- Add required `distro_target` context
- Update ENV variables for RHUI tests
- Update plan filters
- Enable upgrade path to 8.10 on AWS

2024-06-07 11:31 UTC, mkluson requested changes

2024-06-07 11:31 UTC, mkluson commented on .packit.yaml
>    # NOTE(ivasilev) Unfortunately to use yaml templates we need to rewrite the whole tf_extra_params dict
this comment seems connected to the deleted lines

2024-06-07 11:31 UTC, mkluson commented on .packit.yaml
> +            distro_target: "rhel-9.4"
Please make sure all `environments` has `BusinessUnit: sst_upgrades@leapp_upstream_test`

2024-06-07 12:06 UTC, mkluson approved these changes

2024-06-10 05:11 UTC, fernflower approved these changes
Lgtm!

2024-06-10 07:25 UTC, merged