Fix IPU being blocked by resource limitations
oamg/leapp-repository pull request #1256
Opened 2024-06-20 08:19 UTC by tomasfratrik

First resource limit is maximum number of open file descriptors limit, second one being limit for maximum writable file size.

With resource lib we set the limit for the current process (tested with my testing scripts) and its children processes. By testing pre-upgrade and upgrade I found a threshold of max. open file descriptors to be around 512, (the default value for ulimit -n is 1024) so a small multiplier of the default value shouldn't be a problem to set. With writing size there shouldn't be a problem to set it to "infinity".

Both problems from the tickets were solved, but there could be other side effects.

Resolves: RHEL-26459 and RHEL-16881

2024-06-24 15:12 UTC, matejmatuska commented
/packit copr-build

2024-06-27 20:48 UTC, fernflower commented
/packit test

2024-06-28 18:06 UTC, matejmatuska commented
> I don't really like the redundancy of code here, but I'm not sure where should the common logic be placed.

I think `commands/command_utils.py` is an option. There is already some code the commands share.

2024-07-01 13:34 UTC, matejmatuska commented
/packit retest-failed

2024-07-02 09:58 UTC, tomasfratrik commented
> > I don't really like the redundancy of code here, but I'm not sure where should the common logic be placed.
> 
> I think `commands/command_utils.py` is an option. There is already some code the commands share.

Thanks, I put it there

2024-07-02 12:04 UTC, pirat89 commented
/packit copr-build

2024-07-04 09:55 UTC, pirat89 commented
all standard tests passed. executing extended tests

2024-07-04 09:55 UTC, pirat89 commented
/packit test

2024-07-04 09:56 UTC, pirat89 commented
ah.. I thought it's different PR :D mama mia!

2024-10-31 19:50 UTC, matejmatuska commented
/packit retest-failed

2024-11-01 16:04 UTC, matejmatuska requested changes
Tested for both maximum file size and maximum open fd's, works as expected.

However unit tests are missing.

2024-11-04 13:48 UTC, tomasfratrik commented
Latest push squashes commits.

2024-11-04 14:55 UTC, tomasfratrik commented
Unit tests were added.

2024-11-06 20:48 UTC, matejmatuska approved these changes
LGTM

NOTE: If this breaks local tests in containers for you, just rebuild them (make `clean_containers` and then it will be rebuilt the next time you run `make test_container`)

2024-11-07 12:37 UTC, merged