Add actor for mysql migration RHEL9->RHEL10
oamg/leapp-repository pull request #1321
Opened 2024-12-18 09:22 UTC by SlouchyButton

Basic actor that just checks that the mysql-server package is installed and inform user if so.

There are incompatibilities, so there is an article attached describing the process (the article is WIP)

2024-12-18 09:27 UTC, SlouchyButton commented
/packit copr-build

2025-01-07 15:41 UTC, SlouchyButton commented
Added configuration checks, so the user is informed that current MySQL configuration won't be compatible with newer MySQL present in RHEL 10.

When incompatible config is detected, severity is also raised to HIGH, as proceeding will result in `mysqld` failing to launch until issues with config are resolved.

2025-01-08 14:04 UTC, pirat89 commented
@SlouchyButton  hi \o thanks for the contribution! regarding the severity, if I understand it right, the worst scenario here is that mysqldb will not be launched on the new system - will not be working - until they fix the configuration.

- High - Very likely to result in a deteriorated system state.
- Medium - Can impact both the system and applications.
- Low - Should not impact the system but can have an impact on applications.
- Info - Informational with no expected impact to the system or applications.

2025-01-09 15:43 UTC, SlouchyButton commented
Hi @pirat89 
Thank you, taking a look at this. I was originally planning on requesting a review today anyway.
Regarding the severity, what u describe makes sense to me. I'll lower the severity - keep the severity same for all cases detected by the actor.

I also have another question regarding tests. Are they required? There is a small sanity test similar to other our database components, which only tests the detection of the package on the system.

Testing other parts of the actor feels a bit problematic to me, as it is starting new commands with subprocess, or reading files (for configuration). Is it mandatory to _somehow_ test even this functionality, and if so what would be your proposed approach for this?

Thank you!

2025-01-10 14:47 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/libraries/mysqlcheck.py
> +import subprocess
the use of subprocess is forbidden in the project. use the run function instead:
```
from leapp.libraries.stdlib import api, CalledProcessError,  run
```

catch CalledProcessError and OSError exceptions when calling `run`.  Here is the definition of the function:
* https://github.com/oamg/leapp/blob/52cd433d58c50c972cc38e3010c0b8dedf2b88f4/leapp/libraries/stdlib/__init__.py#L149

You can check other actors which use the run function for a hint.

2025-01-10 15:05 UTC, pirat89 commented
@SlouchyButton I made just a short overview the last time, we will try to do proper review the next week. Regarding the subprocess, use the `run` function instead. See my comment above. Regarding unit tests. Mocking `run` is usually simple (just set the function to return an output you would expect to obtain - e.g. from a file). Similar for the reading of files. Similar can be done for the `open` builtin function. We can help you with that if you want.

Of course, when some unit-tests are pretty tricky to write and their value would not be high, it is ok to mention it in a comment (in the test script file) for others and keep the testing on integration tests, etc. The full coverage is not required. Also, in such a case, you could still add files with example outputs under `tests/files/` directory so people can see some examples of outputs at least. And it could help them if they would like to create some tests based on these IO data.

I will cover such tips into the guidelines/tutorials we are writting in these days.

2025-01-10 15:38 UTC, SlouchyButton commented
>  Regarding the subprocess, use the `run` function instead. See my comment above.

Oh, I must have missed it in the docs, will change this.

> I will cover such tips into the guidelines/tutorials we are writting in these days.

That would be great, the documentation/guidelines are great, but they sometimes do feel like they miss some edge cases. Originally I was wanting to do multiple reports but eventually figured you can't do that from one actor and can't have more actors in one folder. I think this isn't explicitely mentioned so maybe some guidelines (best practices) how to report multiple things relating to one task (package upgrade) might help others.

> Update: but I would suggest anyway to postpone writing of another unit-tests until someone do a better review - so they will not need to be rewritten in case of bigger changes.

Right that's a good point.

2025-01-10 17:07 UTC, pirat89 commented
> > Regarding the subprocess, use the `run` function instead. See my comment above.
> 
> Oh, I must have missed it in the docs, will change this.
> 
> > I will cover such tips into the guidelines/tutorials we are writing in these days.
> 
> That would be great, the documentation/guidelines are great, but they sometimes do feel like they miss some edge cases. Originally I was wanting to do multiple reports but eventually figured you can't do that from one actor and can't have more actors in one folder. I think this isn't explicitly mentioned so maybe some guidelines (best practices) how to report multiple things relating to one task (package upgrade) might help others.
> 
> > Update: but I would suggest anyway to postpone writing of another unit-tests until someone do a better review - so they will not need to be rewritten in case of bigger changes.
> 
> Right that's a good point.

well, you can create e.g. `mysql` directory and create several actors inside (each one in a separate dir). let's maybe rather sync the next week to tell us what everything you would like to do, so we can guide you what is the best way to do it :)

2025-01-17 11:00 UTC, pirat89 requested changes
This will need several changes. Also, checking the current solution, I think that it should be pretty simple to cover the complete functionality by unit-tests. let's sync about it yet.

2025-01-17 11:00 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/libraries/mysqlcheck.py
> +                self.report_server_inst_summary += f"{arg} in SystemD service override\n"
This will lead to "lot of" (depending on number of possible entries) text redundancy which is not accepted well by customers. I expect this will not generate usually too many lines, however, it's better to introduce the meaning of the list and then just simply list all the stuff. Something like:
```
Following configured MySQL options will are not valid anymore for MySQL on the target system:
    - option1
    - option2
    - ...
Following systemd...:
    - ...
    - ...
```

Also, define please the `FMT_LIST_SEPARATOR = '\n    - '` and use it for the listings so it's consistent between actors. We plan to document this and most likely create a function in the shared library - refactoring all actors to use it. But let's go with the simple formatting now.

2025-01-17 11:00 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/libraries/mysqlcheck.py
> +                'Detected deprecated options:\n'
Using `\n` in the text is not acturally so good as the formatting could look weird in various webUIs. Also the Warning line is not good I would omit it. Basically the hole report is kind of the warning. Now you need to just provide information:
* What is the problem in genera?
* What does it mean for readers? What do you want them to understand? 
* What specifically we discovered that should concern the user? (the list of problematic entities)

In the remediation instructions:
* What should I do?
* Can resolve it before the upgrade?
* Do I have to do something after the upgrade?
* .....

Note that current summary could be confusing for the user as whatever they do, they will see this msg but remediation instructions says they have to deal with it after the upgrade (and the preupgrade part suggest only the backup of data - btw, do you mean actually dump the database?).

2025-01-17 11:00 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/libraries/mysqlcheck.py
> +                                  if arg in stderr}
Use the `run` function from the leapp stdlib. Following code is untested, writting it just on my knees now (expecting the run function has been imported already):

 ```suggestion
        stderr = run(['mysqld', '--validate-config', '--log-error-verbosity=2'], split=False, checked=False)['stderr']
        if 'deprecated' in stderr:
            self.found_options = {
                arg for arg in self.REMOVED_ARGS if arg in stderr
            }
```

2025-01-17 11:00 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/actor.py
> +    tags = (ChecksPhaseTag, IPUWorkflowTag)
The actor is interacting with the system. It needs to be split in two actors:
* scanner scanner - that will collect all important data (facts). Based on the actor code, it seems you want a Model like this (I expect that most likely you will want to change a little bit):
```
class MySQLConfiguration(Model):
    """
    describe the content of the model
    """
    
    removed_options = fields.List(fields.String, default=[])
    """
    Configured options which are removed in RHEL 10 MySQL
    """
    
    systemd_services = fields.List(fields.String, default=[])
    """
    ...
    """
```
* the checker - that consumes particular leapp message(s) and evaluate the situation.

2025-01-17 11:00 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/actor.py
> +    with MySQL installed.
Ideally, describe what the actor is really doing in details.

2025-01-17 12:13 UTC, pirat89 commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/libraries/mysqlcheck.py
> +                'Detected deprecated options:\n'
btw, `update` -> `upgrade` base on RHEL docs:
* update RPMs using `dnf update` - staying on same RHEL X major version
* upgrade -> upgrading to the next system major version

2025-01-21 18:24 UTC, SlouchyButton commented on repos/system_upgrade/el9toel10/actors/mysqlcheck/libraries/mysqlcheck.py
> +                'Detected deprecated options:\n'
`\n` resolved (removed where not necessary).

Wording might still be improved on.

2025-01-23 16:11 UTC, SlouchyButton commented
Most of the changes should be hopefully done. Missing more thorough description of actors and tests.

2025-01-24 16:53 UTC, SlouchyButton commented
With this, all points from review should be hopefully resolved :crossed_fingers:, so I think this is ready for a second round of review.

2025-02-11 12:15 UTC, closed without merging