LocalReposInhibit: Check mirrorlist and metalink too
oamg/leapp-repository pull request #581
Opened 2020-08-24 18:07 UTC by drehak

A repository can have an URL defined in the field `mirrorlist` or `metalink` instead of `baseurl`. Mirrorlist and metalink are mutually exclusive, though baseurl can still be present as a fallback.

Important notes:
- I'm not sure if the bug with addresses starting with `file:///` occurs when it's a metalink/mirrorlist address. Should we regard those as local repos too?
- `baseurl`, `mirrorlist` and `metalink` are all nullable fields but I could find no checks if there's not a forbidden combination of them, e.g. mirrorlist with metalink or none of these fields at all. I know such repos would be invalid, but there are many places in our codebase where they would traceback. Maybe we should check that somewhere.

2020-08-25 07:39 UTC, ZhukovGreen requested changes
Generally looks good to me. But please fix CI first

2020-08-25 11:01 UTC, drehak commented
@ZhukovGreen The CI problems that popped up are existing code not passing trough the new checks in pylint 2.6, released 5 days ago. The linked PR addresses this.

2020-08-27 09:16 UTC, examon commented
leapp-ci build

2020-08-28 05:16 UTC, ZhukovGreen commented
@pirat89 petr, could you pls glance on it. I have some concerns regarding the description in this MR, maybe I miss something. Otherwise looks good to me

2020-08-28 12:29 UTC, pirat89 commented
> - I'm not sure if the bug with addresses starting with file:/// occurs when it's a metalink/mirrorlist address. Should we regard those as local repos too?

Yes, it will occur for the others as well.

> - baseurl, mirrorlist and metalink are all nullable fields but I could find no checks if there's not a forbidden combination of them, e.g. mirrorlist with metalink or none of these fields at all. I know such repos would be invalid, but there are many places in our codebase where they would traceback. Maybe we should check that somewhere.

No, we are not checking it. We are expecting that repositories are wel defined regarding DNF/YUM. We cannot check every piece of system whether is already broken by user or not. As this is one of very basic things (to have properly set repofiles), we do not check that. Difference is in question of duplicated repoids - which we are checking - but it's different story.

2020-08-28 12:47 UTC, ZhukovGreen approved these changes
After @pirat89 answer, I feel safe to approve it. But I believe it is required additional verification task @mmacura311 , right?

2020-09-01 09:45 UTC, merged

2020-09-01 15:55 UTC, drehak commented
@ZhukovGreen @mmacura311 Thanks a lot, guys!