Modify RHUI_CLOUD_MAP as per arch + add some comments
oamg/leapp-repository pull request #586
Opened 2020-09-14 13:05 UTC by Rezney

We found out that on RHEL-ALT ARM arch the el7 RHUI user rpm package have different name.

2020-09-14 17:04 UTC, pirat89 requested changes
Do not use `platform` anywhere. Take the information about the architecture from the actor configuration.
```
self.configuration.architecture

# or
api.current_actor().configuration.architecture
```

2020-09-14 17:04 UTC, pirat89 commented on repos/system_upgrade/el7toel8/actors/checkrhui/actor.py
> +        arch = platform.machine()
```suggestion
        arch = self.configuration.architecture

2020-09-14 17:04 UTC, pirat89 commented on repos/system_upgrade/el7toel8/actors/targetuserspacecreator/libraries/userspacegen.py
> +    arch = platform.machine()
```suggestion
    arch = api.current_actor().configuration.architecture
```

2020-09-16 07:24 UTC, Rezney commented
e2e tests

2020-09-16 09:18 UTC, Rezney commented
e2e tests

2020-09-17 12:37 UTC, RadekBiba commented
Upgrading ARM64 and x86_64 VMs works for me with leapp-repository-0.11.0-0.202009170724Z.e007094.rhui_map_per_arch.el7.noarch in AWS (using RHUI).

2020-09-17 15:16 UTC, pirat89 approved these changes
lgtm. @Rezney  let's celebrate this big milestone  :D

2020-09-17 15:17 UTC, merged