Use more accurate tense in the SELinux messaging
oamg/leapp-repository pull request #614
Opened 2020-11-02 18:22 UTC by AloisMahdal

After `leapp preupgrade`, reviewing results will show this report:

    SElinux relabeling has been scheduled
    SElinux relabeling has been scheduled as the status was permissive/enforcing.

This looks like leapp has already scheduled the relabeling (ie. `touch /.autorelabel`) which is not accurate and would be illegal.  The proposal is to change the tense:

    SElinux relabeling will be scheduled
    SElinux relabeling will be scheduled as the status is permissive/enforcing.

(This is consistent with another messaging from the same actor.)

2020-11-05 01:38 UTC, pirat89 submitted a review, later dismissed

2021-12-17 13:39 UTC, fernflower commented
Could you please rebase against recent master? I'd like to have this merged.

2021-12-17 13:39 UTC, fernflower requested changes
Please rebase.

2022-02-04 11:36 UTC, fernflower commented
/rerun

2022-02-04 11:36 UTC, fernflower submitted a review, later dismissed

2022-02-04 13:26 UTC, fernflower commented
/rerun

2022-02-04 13:26 UTC, pirat89 commented
/rerun

2022-02-04 13:27 UTC, fernflower approved these changes

2022-02-04 18:13 UTC, merged