persistentnetnamesdisable: Fix the issue when 1 eth nic in multiple n…
oamg/leapp-repository pull request #640
Opened 2021-01-29 06:35 UTC by winndows

…ics env

We should only inhibit the upgrade when multiple eth nics exist.
Neverthless, for 1 eth nic in multiple nics env, we should not
fail the upgrade.

Signed-off-by: Liao Pingfang <liao.pingfang@zte.com.cn>

2021-01-29 11:43 UTC, pirat89 commented
@winndows btw, for the rebase, it's not needed to close the PR, remove branch, create new branch and new PR. you can just do the rebase (in the branch you want to update) like:
```
git fetch origin master
git rebase origin/master
git push --force
```

opening new PRs and closing the old is not good practice as the communication is left in the old one. thanks :)

2021-01-30 14:23 UTC, winndows commented
> @winndows btw, for the rebase, it's not needed to close the PR, remove branch, create new branch and new PR. you can just do the rebase (in the branch you want to update) like:
> 
> ```
> git fetch origin master
> git rebase origin/master
> git push --force
> ```
> 
> opening new PRs and closing the old is not good practice as the communication is left in the old one. thanks :)
> 
> More about `git rebase` is here: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

Got it. Thank you very much.

2021-02-22 17:37 UTC, pirat89 commented
Actually, thinking about that, I am not sure this is correct. Are we sure that when multiple network interfaces are present and just one is ethX, that it will be unchanged? I mean, e.g. from eth0 to eth1? Is the eth naming from udev always incremental in case of ethX, or is it taking the name from kernel? As I understand, kernel by default names all interfaces ethX and  udev renames these subsequently. 

@msekletar Michal, can tell us how is it in this case? I know that even RH article speak just about cases when multiple ethX interfaces are present and we discussed that in the part. So I want to rather double-ensure about that for the last time.

2021-02-22 18:10 UTC, pirat89 commented
@msekletar Thank Michal for fast answer. However I am not sure whether I get it. from the first sentence. For crystal clear check, can you confirm the table is valid or correct me?:
```
list of interfaces | inhibitor
===================|========
eth0               | N
-------------------|------------
net0, net1,...     | N
-------------------|------------
eth0, eth1         | Y
-------------------|------------
eth0, net0         | Y
-------------------|------------
eth0, eth1, net0   | Y
```

2021-02-22 18:43 UTC, msekletar commented
@pirat89 you got it right, table is correct.

2021-02-23 10:16 UTC, pirat89 commented
@winndows  Hi man, so the upstream code is actually ok. What is wrong is the report message. Do you want to change your PR to fix the message instead or should I close it? I am going to report the RH documentation to ensure it's fixed.

2021-02-23 10:17 UTC, pirat89 requested changes
the original code is actually ok. the report message is unclear.

2021-02-23 14:16 UTC, winndows commented
@pirat89 Please help to close this request, thanks a lot.

2021-02-24 17:20 UTC, pirat89 commented
@winndows  if you drop your changes and update the report like below, it's possible to merge it:
```diff
             create_report([
                 reporting.Title('Unsupported network configuration'),
                 reporting.Summary(
-                    'Detected multiple network interfaces using unstable kernel names (e.g. eth0, eth1). '
+                    'Detected multiple physical network interfaces where one or more use kernel naming (e.g. eth0). '
                     'Upgrade process can not continue because stability of names can not be guaranteed. '
                     'Please read the article at https://access.redhat.com/solutions/4067471 for more information.'
                 ),
+                reporting.ExternalLink(
+                    title='How to perform an in-place upgrade to RHEL 8 when using kernel NIC names on RHEL 7',
+                    url='https://access.redhat.com/solutions/4067471'
+                ),
+                reporting.Remediation(
+                    hint='Rename all ethX network interfaces following the attached KB solution article.'
+                ),
                 reporting.Severity(reporting.Severity.HIGH),
                 reporting.Tags([reporting.Tags.NETWORK]),
                 reporting.Flags([reporting.Flags.INHIBITOR])
```

2021-02-27 12:57 UTC, pirat89 approved these changes

2021-02-27 12:58 UTC, pirat89 commented
@winndows please make the pylint happy.

2021-03-01 12:06 UTC, pirat89 commented
@winndows I am sorry I forget to inform you. The CI is failing because of the new pylint that was released in last days (+ internal issues). See  https://github.com/oamg/leapp-repository/pull/647 - once the #647 PR is merged this one needs to be rebased to pass tests.

2021-03-01 13:32 UTC, pirat89 commented
@winndows Merge. Rebase please against the master.

2021-03-02 13:28 UTC, pirat89 commented
leapp-ci build

2021-03-05 06:11 UTC, winndows commented
leapp-ci build

2021-03-08 20:17 UTC, pirat89 commented
leapp-ci build

2021-06-25 14:52 UTC, pirat89 commented
@winndows I am sorry we have forgotten this PR. please rebase it against up-to-date master and fix unit-tests. After that we can merge it.

2021-07-20 02:19 UTC, winndows commented
> @winndows I am sorry we have forgotten this PR. please rebase it against up-to-date master and fix unit-tests. After that we can merge it.

@pirat89 Could you help to review this change? Thanks a lot.

2021-09-24 17:01 UTC, pirat89 approved these changes
@winndows I am sorry i've missed that. It looks good now. It looks good now. Merging.

2021-09-24 17:01 UTC, merged