Replace leapp-pr-welcome-msg-bot with GitHub action
oamg/leapp-repository pull request #673
Opened 2021-06-07 12:55 UTC by andywaltlova

For working example see [my test repo](https://github.com/andywaltlova/actions_test_space/pull/14)

(Same [PR in leapp](https://github.com/oamg/leapp/pull/712))

2021-06-09 12:12 UTC, Wecros requested changes
Otherwise looks good. Good job with linking the private test repo :+1: Will merge after the change.

2021-06-09 12:12 UTC, Wecros commented on .github/workflows/pr-welcome-msg.yml
> +# In this workflow should NOT be checkout action - because of security reasons.
should -> there should

2021-06-09 12:13 UTC, Wecros commented
Hmm, not sure why the `e2e` tests are failing. But I would guess the issue is not related to this PR.

2021-06-09 13:23 UTC, andywaltlova commented on .github/workflows/pr-welcome-msg.yml
> +# In this workflow should NOT be checkout action - because of security reasons.
Fixed

2021-06-09 13:55 UTC, Wecros approved these changes

2021-06-11 09:18 UTC, pirat89 commented
leapp-ci build

2021-06-15 13:09 UTC, Wecros approved these changes

2021-06-18 11:26 UTC, fernflower commented
leapp ci-build

2021-06-18 11:32 UTC, fernflower commented
/rerun

2021-06-18 12:26 UTC, fernflower commented
/rerun

2021-06-21 08:29 UTC, jmikovic approved these changes

2021-06-21 08:29 UTC, merged