Replace systemd-mount with pyudev.
oamg/leapp-repository pull request #711
Opened 2021-08-26 11:02 UTC by MichalHe

Replace `systemd-mound --list` with _pyudev_.

The current implementation of the _StorageScanner_ actor relies on calling `systemd-mount --list` and parsing its output. Since the command output is not provided in a format that is easy to parse (the data is formatted as a pretty table padded with whitespace) it is error prone to parse it by hand.

This PR replaces the call to `system-mount --list` with the usage of the _pyudev_ library, obtaining the very same information in the same way as  `system-mount --list` does. 

Current status:
- [x] fix unit tests relying on mocking `systemd-mount` command outputs
- [x] manually verify that the messages produced by the old implementation and the new one are the same

2021-09-22 15:01 UTC, Rezney requested changes
Apart from the small typo LGTM. Message in the DB seems to be correct:
```
"systemdmount": [
    {"fs_type": "xfs", "label": "n/a", "model": "n/a", "node": "/dev/vda1", "path": "pci-0000:00:02.0", "uuid": "7d8635ff-fb7c-4e9f-a1ef-13ad8de15b9b", "wwn": "n/a"}, 
    {"fs_type": "xfs", "label": "n/a", "model": "n/a", "node": "/dev/dm-0", "path": "n/a", "uuid": "f3f6c711-f75f-4bd6-af5a-78d590e7fd7d", "wwn": "n/a"}]
```

2021-09-24 17:05 UTC, pirat89 commented on repos/system_upgrade/common/actors/storagescanner/libraries/storagescanner.py
> +    from udev directly using pyudev. The systemd-mount output parsing has proved not to be unreliable due to
done as part of rebasing (fyi @MichalHe )

2021-09-24 17:05 UTC, pirat89 approved these changes

2021-09-25 08:34 UTC, Rezney approved these changes

2021-10-08 12:55 UTC, pirat89 commented
@MichalHe pls one new rebase

2021-10-08 13:03 UTC, pirat89 submitted a review, later dismissed
thanks :)

2021-11-24 14:35 UTC, pirat89 commented
@MichalHe pls one more rebase. we are going to finish this one soon.

2021-11-25 10:14 UTC, mkluson commented
/rerun

2021-11-25 13:20 UTC, fernflower commented
leapp-ci build

2021-11-29 09:53 UTC, pirat89 commented
/rerun

2021-11-29 12:15 UTC, pirat89 approved these changes

2021-11-29 12:16 UTC, merged