[WIP] add actor that reports removed rhel-9 packages
oamg/leapp-repository pull request #785
Opened 2022-01-03 16:11 UTC by ZoltanFridrich

These packages have been removed between RHEL-8 and RHEL-9:
compat-openssl10, fipscheck, openssh-cavs, openssh-ldap, pinentry-emacs, pinentry-gtk, pyopenssl
Create an actor that checks if these packages are installed on the system and inhibit the upgrade process in that case.

2022-01-03 17:11 UTC, pirat89 commented
@ZoltanFridrich Hi, could we sync over vcall about this PR? I am little bit confused about the purpose. I mean, there are hundreds of packages removed between RHEL X systems. Why these packages should inhibit the upgrade? I have more points to discuss, but in case you have time for a vcall, i think it will be faster.

2022-01-14 13:01 UTC, pirat89 requested changes
As discussed on our sync call, the inhibitor in this case does not make sense. As well, the actor does not seem to provide any benefit right now. Try to answer these questions when thinking about the solution:
* What is the user actually supposed to do after seeing this msg?
* What is impact on user regarding the "removed" packages after the upgrade?
* Regarding the PES db, there are many packages that are going to be removed during IPU 8 -> 9. What is the difference in the context of other XXX removed packages that are not reported, to report explicitly the removal of these packages?

2022-01-24 13:22 UTC, pirat89 commented
@ZoltanFridrich  as the internal jira ticket has been closed, I guess this one is supposed to be closed as well. Feel free to reopen if not.

2022-01-24 13:22 UTC, closed without merging

2022-01-24 14:17 UTC, ZoltanFridrich commented
I was just waiting if there will be any other comments on the jira ticket. As it got closed on jira it is ok to close this PR. Thank you.