Fix bug with existing symlink in handleyumconfig
oamg/leapp-repository pull request #811
Opened 2022-01-20 14:16 UTC by brianjmurrell

If the source is already a symlink to the destination handleyumconfig
will fail.

Fixes: #810

2022-01-21 16:33 UTC, examon commented
leapp-ci build

2022-01-23 01:02 UTC, pirat89 requested changes

2022-01-23 12:56 UTC, brianjmurrell commented on repos/system_upgrade/el7toel8/tools/handleyumconfig
> +    fi
Oh, yes of course.  Using the arguments (`$1` and `$2`) was my intention.  I just forgot to do the substitution when I pasted from my test.  :-(

2022-01-24 13:21 UTC, pirat89 approved these changes

2022-01-24 13:22 UTC, pirat89 commented
/rerun

2022-01-24 17:22 UTC, merged

2022-01-24 17:22 UTC, pirat89 commented
Thanks for the contribution!!