adjust satellite versioning
oamg/leapp-repository pull request #857
Opened 2022-03-14 15:32 UTC by evgeni

2022-03-14 15:40 UTC, pirat89 commented
@evgeni any more info about the change? Is it expected to be still part of this release?

2022-03-14 16:26 UTC, pirat89 submitted a review, later dismissed

2022-03-15 07:12 UTC, vinzenz approved these changes

2022-03-15 07:14 UTC, vinzenz requested changes
Sorry for removing approval - But I just noticed that there is no commit message - This is a common practice so please add a commit message and sign off your commit. Thanks.

2022-03-15 07:24 UTC, vinzenz approved these changes

2022-03-15 07:35 UTC, merged