[WIP] el8toel9: Warn about the NVIDIA driver before upgrade
oamg/leapp-repository pull request #880
Opened 2022-04-13 08:51 UTC by nielsdg

2022-05-03 12:54 UTC, nielsdg commented
review please

2022-05-03 21:15 UTC, vinzenz requested changes
@nielsdg 
Please run `make lint_fix` to fix the import linter errors

Also please add some test for the actor:
An inspiration for your use case: https://github.com/oamg/leapp-repository/blob/00aa46919b911f93cdb4eeddf90085eda875839e/repos/system_upgrade/el7toel8/actors/checkkdegnome/tests/unit_test_checkkdegnome.py

2022-05-03 21:16 UTC, vinzenz commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/actor.py
> +            nvidia_driver_loaded = any("nvidia" in active_mod.filename for active_mod in fact.kernel_modules)
```suggestion
            nvidia_driver_loaded = any('nvidia' in active_mod.filename for active_mod in fact.kernel_modules)
```

2022-05-04 11:22 UTC, nielsdg commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/actor.py
> +            nvidia_driver_loaded = any("nvidia" in active_mod.filename for active_mod in fact.kernel_modules)
Thanks, fixed!

2022-05-05 09:26 UTC, vinzenz commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/tests/test_nvidiadriver.py
> +    current_actor_context.feed(create_modulesfacts(kernel_modules=without_nvidia))
```suggestion
    current_actor_context.feed(ActiveKernelModulesFacts(kernel_modules=without_nvidia))
```

2022-05-10 11:27 UTC, nielsdg commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/tests/test_nvidiadriver.py
> +    current_actor_context.feed(create_modulesfacts(kernel_modules=without_nvidia))
right, thanks!

2022-05-10 12:12 UTC, vinzenz commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/tests/test_nvidiadriver.py
> +from leapp.snactor.fixture import current_actor_context
```suggestion

```

2022-05-10 12:12 UTC, vinzenz commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/tests/test_nvidiadriver.py
> +from leapp.snactor.fixture import current_actor_context
This is not necessary, and actually unsupported

2022-06-03 14:17 UTC, Rezney commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/actor.py
> +                            'the nouveau drier is blacklisted. If you upgrade now, you will end up without a '
```suggestion
                            'the nouveau driver is blacklisted. If you upgrade now, you will end up without a '
```

2022-06-03 14:19 UTC, Rezney commented on repos/system_upgrade/el8toel9/actors/nvidiaproprietarydriver/actor.py
> +                            'the nouveau drier is blacklisted. If you upgrade now, you will end up without a '
@nielsdg Please fix this typo and we should be good to merge it. Thanks.

2022-06-06 07:49 UTC, vinzenz approved these changes

2022-06-06 09:50 UTC, merged