CheckNFS actor should respect nsfd filesystem
oamg/leapp-repository pull request #888
Opened 2022-05-10 13:00 UTC by fernflower

Check filesystem type for full match with 'nfs'
otherwise false positive fires like in 'nfsd' may
occur.

OAMG-6355

2022-05-13 08:16 UTC, fernflower commented
/rerun

2022-05-19 07:07 UTC, vinzenz approved these changes

2022-05-19 07:09 UTC, vinzenz requested changes
Please add a test case for the nfsd case - Thanks.

2022-05-19 10:44 UTC, fernflower commented
/rerun

2022-05-23 07:54 UTC, fernflower commented
/rerun

2022-05-26 09:33 UTC, Rezney commented
/rerun

2022-05-26 13:11 UTC, Rezney approved these changes

2022-05-26 13:11 UTC, merged