Add dialog for all VDO converted.
oamg/leapp-repository pull request #955
Opened 2022-08-24 17:32 UTC by jshimkus-rh

Skips checking devices.

2022-08-24 17:44 UTC, pirat89 commented
To be honest, I am more thinking about merging both dialogs into the one, raised in the checkphase. Let's discuss it later. running home \o

2022-08-24 18:10 UTC, jshimkus-rh commented
I get that.  There's quite a bit of effective overlap between the two.

2022-08-25 15:25 UTC, smitterl requested changes
Hey, this works for me. There's a minor typo I think we should definitely fix (s. comments).

I'm also wondering if we can't add any information for users to identify for themselves if they even have vdo type volumes. From [RHEL 8 docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/deduplicating_and_compressing_logical_volumes_on_rhel/creating-a-deduplicated-and-compressed-logical-volume_deduplicating-and-compressing-logical-volumes-on-rhel#creating-an-lvm-vdo-volume_creating-a-deduplicated-and-compressed-logical-volume) I hoped to find information via manpage lvmvdo but I can't seem to find the manpage and am not really sure how I could check this. Does somebody know more?

2022-08-25 16:58 UTC, jshimkus-rh commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                    reason='To maximze safety all block devices on a system '
Fixed.

2022-08-25 16:59 UTC, jshimkus-rh commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                           'converted to LVM management.  If the check of any '
Not clear on the issue unless it's the double spaces after '.'?
But I did notice some over 80 situations which I addressed.

2022-08-25 17:00 UTC, jshimkus-rh commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                           'device fails for any reason an upgrade  inhibiting '
Same response as to previous "Too many blanks?"

2022-08-25 17:14 UTC, jshimkus-rh commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                    reason='To maximze safety all block devices on a system '
As to identifying vdo devices...
(note that sdb is a pre-conversion vdo and sdc is post-conversion)
lsblk proudces the following...
`# lsblk

NAME                          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdb                             8:16   0   16G  0 disk 
└─vdo-sdb                     253:3    0   12G  0 vdo  
sdc                             8:32   0   16G  0 disk 
└─vdovg-vdolvol_vpool_vdata   253:4    0   16G  0 lvm  
  └─vdovg-vdolvol_vpool-vpool 253:5    0   12G  0 lvm  
    └─vdovg-vdolvol           253:6    0   12G  0 lvm  `

And 'dmsetup status' produces...
`# dmsetup status

vdo-sdb: 0 25116416 vdo /dev/sdb normal - online online 1050700 4194304
vdovg-vdolvol: 0 25116416 linear 
vdovg-vdolvol_vpool-vpool: 0 25116416 vdo /dev/dm-4 normal - online online 1050188 4193792
vdovg-vdolvol_vpool_vdata: 0 33550336 linear `

But both of those are with the vdo device active.

2022-08-25 17:38 UTC, jshimkus-rh commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                    reason='To maximze safety all block devices on a system '
blkid produces identifying info regardless of the vdo device being active...

`# blkid

/dev/sdb: UUID="9a5cf4a3-8264-48a3-a529-f0b2908d5615" TYPE="vdo"
/dev/sdc: UUID="eJ40K2-d5uF-Ux8g-JBBl-Hh94-u4Ce-XM26vq" TYPE="LVM2_member"`

I was going to include a warning that such identification only worked if the vdo packages were installed and if they'd been uninstalled that blkid no longer identified 'TYPE=vdo' devices.  But in verifying that it's apparently not (or no longer; I'd swear I'd seen it in the past) the case.

2022-08-29 07:39 UTC, smitterl commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                           'device fails for any reason an upgrade  inhibiting '
`upgrade  inhibiting`

2022-08-29 07:41 UTC, smitterl commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                    reason='To maximze safety all block devices on a system '
> # lsblk
> 
> NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT sdb 8:16 0 16G 0 disk └─vdo-sdb 253:3 0 12G 0 vdo sdc 8:32 0 16G 0 disk └─vdovg-vdolvol_vpool_vdata 253:4 0 16G 0 lvm └─vdovg-vdolvol_vpool-vpool 253:5 0 12G 0 lvm

Thank you. What about we add a note "E.g. you can see if you are using vdo at all by running `lsblk|grep vdo`; an empty output will confirm there are no vdo volumes."

2022-08-29 07:42 UTC, smitterl approved these changes

2022-08-29 07:42 UTC, smitterl commented
@jshimkus-rh The PR is in "Draft" status, is this on purpose?

2022-08-29 11:02 UTC, pirat89 commented
> @jshimkus-rh The PR is in "Draft" status, is this on purpose?

yes, we are discussing the right solution and most probably we will go with a different one where we merge both dialogs.

2022-08-29 11:16 UTC, jshimkus-rh commented
> On Aug 29, 2022, at 07:02, Petr Stodůlka ***@***.***> wrote:
> 
> ﻿
> @jshimkus-rh The PR is in "Draft" status, is this on purpose?
> 
> yes, we are discussing the right solution and most probably we will go with a different one where we merge both dialogs.
> 

Petr, did you see my email re the single dialog?  Perhaps I missed them?
I wanted your comments before making a PR. 

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-08-29 13:03 UTC, jshimkus-rh commented on repos/system_upgrade/el8toel9/actors/checkvdo/actor.py
> +                           'device fails for any reason an upgrade  inhibiting '
Saw that after, but the reflow for >80 cols cleaned it up.

2022-08-30 11:56 UTC, jshimkus-rh commented
Closing this PR.  New PR  #961 collapsing to a single dialog is  its replacement.

2022-08-30 11:56 UTC, closed without merging