Provide common system information about services
oamg/leapp-repository pull request #959
Opened 2022-08-26 14:53 UTC by matejmatuska

Jira ref.: OAMG-1812

2022-09-05 10:25 UTC, pirat89 commented on repos/system_upgrade/common/models/systemdservices.py
> +        'bad'
sort

2022-11-01 18:56 UTC, pirat89 requested changes
Seems good to me, discovered mostly just minor (docstrings, ..). I need to think about couple of things yet and do some changes before the merge (+ testing & squash).

note: rebased + added a commit with todo/fixme notes and mini refactoring (I choosed this time this way instead of comment in the webpage. all notes will be dropped when done).

2022-11-14 20:25 UTC, pirat89 commented
@matejmatuska the second commit is supposed to be squashed into the first one. I've been thinking about separating it into more commits but it seems simple enough to actually have just one commit. I did the split of the error handling into the actors in the end as it seems to me more clean, adding info about the raised exceptions into docstrings.

Bigger change is around the *target* msgs. I've decided in in case of errors to not produce particular target msgs so it's easy to desntiguish between valid and invalid content - hence, this is still discussable part. So I plan to merge that tomorrow after someone else confirm it's the way to go (ping: @oamg/developers )

2022-11-15 10:54 UTC, pirat89 commented
/packit build

2022-11-15 15:30 UTC, Rezney approved these changes

2022-11-15 15:53 UTC, merged