Rework network configuration handling
oamg/leapp-repository pull request #969
Opened 2022-09-26 11:32 UTC by lkundrak

This splits off the ifcfg & NetworkManager profile reading parts from CheckIfCfg and CheckNetworkDeprecations into separate scanners; allowing the ifcfg code to be shared.

There's a bugfix at the end, depending on the IfCfg parsing consolidation.

2022-09-26 13:20 UTC, lkundrak commented
review please

2022-09-27 11:25 UTC, pirat89 commented
@lkundrak hi, is there a BZ for this? It seems to me familiar but not sure. if there is, please add the link into the description. we will get to the review today/tomorrow (putting on my todo)

2022-09-30 09:10 UTC, lkundrak commented
> @lkundrak hi, is there a BZ for this? It seems to me familiar but not sure.

Only for the last change. Instead of applying it in two different places, I ended up moving the code into a scanner actor, as (I think) you advised before.

> if there is, please add the link into the description.

Done.

2022-10-04 19:59 UTC, pirat89 commented
@lkundrak thanks! I am sorry for the postponed review (urgent looong bug investigation). It seems we get to review in the end of this week.

2022-10-17 13:23 UTC, pirat89 requested changes

2022-10-19 06:55 UTC, pirat89 commented on repos/system_upgrade/el8toel9/actors/networkdeprecations/tests/unit_test_networkdeprecations.py
> +            NetworkManagerConnectionProperty(name='wep-key0', value='abcde'),
@lkundrak so we discussed the secrets solution and for now, implement an allowlist of keys for which you need (and store) the value and for the others set None. We will investigate a better solution around secrets for the future but right now let's go just in this way.

2022-11-03 14:15 UTC, lkundrak commented
Pushed new version for review.

The major change is the omission of the secrets. Easy for ifcfg (where secrets are in a separate file), but for keyfiles we need to utilize libnm via GObject introspection. That won't be there on python2 platforms (no biggie, we're concerned about el8 and later only) and on UBI (used for testing, not NetworkManager there at all).

2023-01-18 16:22 UTC, pirat89 commented
review in progress

2023-01-18 16:22 UTC, pirat89 commented
/rerun

2023-01-20 21:14 UTC, pirat89 commented on repos/system_upgrade/el8toel9/actors/networkmanagerconnectionscanner/libraries/networkmanagerconnectionscanner.py
> +    err_details = 'python3-gobject-base package is not available'
@lkundrak  I need to sync  with you about this as probably the package should have updated requirement. Let's sync on monday.

2023-01-25 10:09 UTC, pirat89 commented on repos/system_upgrade/el8toel9/actors/networkmanagerconnectionscanner/libraries/networkmanagerconnectionscanner.py
> +    err_details = 'python3-gobject-base package is not available'
@lkundrak unfortunately I do not have permissions to update your branch. So I pushed the changes to my fork. Please update your branch when you are online, so we can merge it: https://github.com/pirat89/leapp-repository/tree/lr/ifcfg-nm-rework

2023-01-27 09:26 UTC, pirat89 approved these changes
merging \o/ thanks for the contribution!

2023-01-27 09:26 UTC, merged